title: כל הטופ
subtitle: ורק הטופ
description: כל הטופ הינו בלוג המכיל המלצות לטיולים, גאדג'טים, ריכוליות ועוד!
keywords: >-
  רכילות, ריכולים, סלבריטים, טיולים, יוון, דרום אמריקה, טיול אחרי צבע,
  טכנולוגיה, חרבות ברזל, ריכול, טיול, אהבה, הלם
author: איילה
language: en
timezone: Asia/Jerusalem
avatar: https://cdn.jsdelivr.net/gh/OfirApps/files@main/favicon/favicon-150x150.png
url: https://kolha.top/
root: /
permalink: ':title/'
permalink_defaults: null
pretty_urls:
  trailing_index: false
  trailing_html: false
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render:
  - README.md
  - '**/*.html'
  - manifest.json
  - start
  - CNAME
  - robots.txt
  - assets/*
new_post_name: ':title.md'
default_layout: post
auto_spacing: true
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: false
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: '    '
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map:
  אוסף-אטרקציות: אוסף
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: false
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: icarus
deploy:
  - type: git
    repo: git@xaoxuu.com:xaoxuu/volantis.git
    branch: master
    message: Github CI Auto Builder at {{ now('YYYY-MM-DD HH:mm:ss Z') }}
import:
  head_begin:
    - <meta name="msapplication-TileColor" content="#ffffff">
    - >-
      <meta name="msapplication-config"
      content="https://cdn.jsdelivr.net/gh/OfirApps/files@main/favicon/browserconfig.xml">
    - <meta name="theme-color" content="#ffffff">
    - >-
      <link rel="apple-touch-icon" sizes="180x180"
      href="https://cdn.jsdelivr.net/gh/OfirApps/files@main/favicon/apple-touch-icon.png">
    - >-
      <link rel="icon" type="image/png" sizes="32x32"
      href="https://cdn.jsdelivr.net/gh/OfirApps/files@main/favicon/favicon-32x32.png">
    - >-
      <link rel="icon" type="image/png" sizes="16x16"
      href="https://cdn.jsdelivr.net/gh/OfirApps/files@main/favicon/favicon-16x16.png">
    - >-
      <link rel="manifest"
      href="https://cdn.jsdelivr.net/gh/OfirApps/files@main/favicon/site.webmanifest">
    - >-
      <link rel="mask-icon"
      href="https://cdn.jsdelivr.net/gh/OfirApps/files@main/favicon/safari-pinned-tab.svg"
      color="#5bbad5">
    - >-
      <link rel="shortcut icon"
      href="https://cdn.jsdelivr.net/gh/OfirApps/files@main/favicon/favicon.ico">
    - <meta name="apple-mobile-web-app-title" content="כל הטופ">
    - <meta name="application-name" content="כל הטופ">
    - <meta name="msapplication-TileColor" content="#f4f4f4">
    - >-
      <meta name="msapplication-TileImage"
      content="https://cdn.jsdelivr.net/gh/OfirApps/files@main/favicon/favicon-32x32.png">
    - >-
      <meta name="theme-color" content="#f4f4f4" media="(prefers-color-scheme:
      light)">
    - >-
      <meta name="theme-color" content="#121212" media="(prefers-color-scheme:
      dark)">
    - >-
      <script
      src="https://cdn.jsdelivr.net/gh/OfirApps/files@48266cfcffaa773708397c038eb4018de0ffc4b2/ect.js"
      defer></script>
    - >-
      <link rel="stylesheet" type="text/css" media="print"
      href="/print_version.css">
    - >-
      <script async
      src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8577850668418356"
      crossorigin="anonymous" defer></script>
  head_end: null
  body_begin: null
sitemap:
  path: sitemap.xml
  tag: false
  category: false
neat_enable: true
hide_posts:
  enable: true
  filter: hidden
  noindex: true
nofollow:
  enable: true
  exclude:
    - kolha.top
autoprefixer:
  exclude:
    - '*.min.css'
marked:
  gfm: true
  pedantic: false
  breaks: true
  smartLists: true
  smartypants: false
  modifyAnchors: 0
  autolink: true
  sanitizeUrl: false
  headerIds: true
  prependRoot: false
  external_link:
    enable: true
    exclude: []
    nofollow: true
